port: 8080
mysql:
  host: localhost
  port: 3306
  user: root
  password: new-password
  db: rainbowApp
app:
  appId: jeFLCP1T
  appSecret: sofoLyjrcwxcj6ec
discordBotToken: MTAwODczNzczODY2NjgwNzQxNg.GTER6T.4cNuhVz80DtwNvwIVOjNBphSX4VQfom072dNJY
dodoBot:
  clientId: 78090178
  tokenId: NzgwOTAxNzg.0qcX77-9.sKRfWBHzGpvgZaHBoFp_4oDjixM0leJ5H1EmDEdjofw
botAddress: cfxtest:aarep2p1rcadt0j1x0gkybggfkk97uxwty45grxxt7
jwtKeys:
  openapi: jwt-openapi-key
customMint:
  mintRespPrefix: https://testnet.confluxscan.io/nft/
proxy: http://172.31.192.1:7890
advertise: Powered by NFTRainbow


