port: 8080
mysql:
  host: localhost
  port: 3306
  user: root
  password: new-password
  db: service
discordBotToken:
dodoBot:
  clientId:
  tokenId:
jwtKeys:
  openapi: jwt-openapi-key
  dashboard: jwt-dashboard-key
customMint:
  mintRespPrefix: https://testnet.confluxscan.io/nft/
proxy: http://0.0.0.0:7890
advertise: Powered by NFTRainbow
newYearEvent:
  newYearCommonId: c857bbe8
  newYearSpecialId: 0c3ba1c4
  commonMintLimit: 5
  everyDaySharerLimit: 3
  ipLimitEveryday: 100
rainbowDashboardApi: https://dev.nftrainbow.xyz
rainbowOpenApi: https://dev.nftrainbow.xyz
env: dev
testMinuteDuration: 50
rpcs:
  mainnet: https://main.confluxrpc.com
  testnet: https://test.confluxrpc.com
startTime: 1673937000
imagesDir:
  minted: service/images/minted
  nonMinted: service/images/nonMinted
posterDir:
  activity: service/activity/
  result: service/result/
oss:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName: nft-
url:
  activity: https://apps.nftrainbow.cn/
