port: 8080
mysql:
  host: localhost
  port: 3306
  user: root
  password: new-password
  db: rainbowApp
discordBotToken: MTAwODczNzczODY2NjgwNzQxNg.GTER6T.4cNuhVz80DtwNvwIVOjNBphSX4VQfom072dNJY
dodoBot:
  clientId: 78090178
  tokenId: NzgwOTAxNzg.0qcX77-9.sKRfWBHzGpvgZaHBoFp_4oDjixM0leJ5H1EmDEdjofw
jwtKeys:
  openapi: jwt-openapi-key
  dashboard: jwt-dashboard-key
customMint:
  mintRespPrefix: https://testnet.confluxscan.io/nft/
proxy: http://0.0.0.0:7890
advertise: Powered by NFTRainbow
newYearEvent:
  newYearCommonId: 14
  newYearSpecialId: 15
  commonMintLimit: 5
  everyDaySharerLimit: 3
  ipLimitEveryday: 100
rainbowDashboardApi: https://console.nftrainbow.cn
rainbowOpenApi: https://api.nftrainbow.cn
env: dev
testMinuteDuration: 30
rpcs:
  mainnet: https://main.confluxrpc.com
  testnet: https://test.confluxrpc.com
startTime: 1673937000