package enums

type BatchMintStatus uint

const (
	BATCH_MINT_STATUS_MINT_FAIL = iota - 2
	BATCH_MINT_STATUS_CREATE_WALLET_FAIL
	BATCH_MINT_STATUS_INIT
	BATCH_MINT_STATUS_CREATE_WALLET
	BATCH_MINT_STATUS_MINT
)
